2021-02-17 19:39:59,120 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2021-02-17 19:39:59,120 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\instabot\bot\bot.py
2021-02-17 19:39:59,120 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2021-02-17 19:40:00,368 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [200]>
2021-02-17 19:40:01,064 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [200]>
2021-02-17 19:40:01,750 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [200]>
2021-02-17 19:40:22,809 - instabot version: 0.117.0 (api) - WARNING - HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/accounts/contact_point_prefill/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001A3E4EC0CD0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2021-02-17 19:40:25,963 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/login/ returned response: <Response [200]>
2021-02-17 19:40:25,963 - instabot version: 0.117.0 (api) - INFO - Logged-in successfully as 'deepfriedmemes14'!
2021-02-17 19:40:26,016 - instabot version: 0.117.0 (api_login) - INFO - LOGIN FLOW! Just logged-in: True
2021-02-17 19:40:27,241 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [200]>
2021-02-17 19:40:28,145 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [200]>
2021-02-17 19:40:29,466 - instabot version: 0.117.0 (api) - DEBUG - GET to endpoint: zr/token/result/?device_id=android-323d6b44c01eb352&token_hash=&custom_device_id=android-323d6b44c01eb352&fetch_reason=token_expired returned response: <Response [200]>
2021-02-17 19:40:29,834 - instabot version: 0.117.0 (api) - DEBUG - GET to endpoint: multiple_accounts/get_account_family/ returned response: <Response [200]>
2021-02-17 19:40:30,234 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [200]>
2021-02-17 19:40:30,685 - instabot version: 0.117.0 (api) - DEBUG - GET to endpoint: igtv/browse_feed/?prefetch=1 returned response: <Response [200]>
2021-02-17 19:40:31,058 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: creatives/ar_class/ returned response: <Response [200]>
2021-02-17 19:40:31,694 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: feed/reels_tray/ returned response: <Response [200]>
2021-02-17 19:40:34,112 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: feed/timeline/ returned response: <Response [200]>
2021-02-17 19:40:34,497 - instabot version: 0.117.0 (api) - DEBUG - GET to endpoint: media/blocked/ returned response: <Response [200]>
2021-02-17 19:40:35,113 - instabot version: 0.117.0 (api) - DEBUG - GET to endpoint: news/inbox/ returned response: <Response [200]>
2021-02-17 19:40:35,691 - instabot version: 0.117.0 (api) - DEBUG - GET to endpoint: loom/fetch_config/ returned response: <Response [200]>
2021-02-17 19:40:56,747 - instabot version: 0.117.0 (api) - WARNING - HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/scores/bootstrap/users/?surfaces=%5B%22autocomplete_user_list%22,%22coefficient_besties_list_ranking%22,%22coefficient_rank_recipient_user_suggestion%22,%22coefficient_ios_section_test_bootstrap_ranking%22,%22coefficient_direct_recipients_ranking_variant_2%22%5D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001A3E4EEA550>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2021-02-17 19:40:57,816 - instabot version: 0.117.0 (api) - DEBUG - GET to endpoint: business/eligibility/get_monetization_products_eligibility_data/?product_types=branded_content returned response: <Response [200]>
2021-02-17 19:40:58,417 - instabot version: 0.117.0 (api) - DEBUG - GET to endpoint: business/branded_content/should_require_professional_account/ returned response: <Response [200]>
2021-02-17 19:41:19,460 - instabot version: 0.117.0 (api) - WARNING - HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/linked_accounts/get_linkage_status/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001A3E4F1FA00>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2021-02-17 19:41:20,008 - instabot version: 0.117.0 (api) - DEBUG - GET to endpoint: locations/request_country/ returned response: <Response [200]>
2021-02-17 19:41:20,378 - instabot version: 0.117.0 (api) - DEBUG - GET to endpoint: qp/get_cooldowns/?signed_body=signed_body=4b9c516a5410a3bc128e09c6104a7f042146b9c2023870560c63a43a7f66781c.4&ig_sig_key_version=4&ig_sig_key_version=4 returned response: <Response [200]>
2021-02-17 19:41:20,763 - instabot version: 0.117.0 (api) - DEBUG - GET to endpoint: users/arlink_download_info/?version_override=2.2.1 returned response: <Response [200]>
2021-02-17 19:41:21,227 - instabot version: 0.117.0 (api) - DEBUG - GET to endpoint: users/45876683957/info/ returned response: <Response [200]>
2021-02-17 19:41:21,712 - instabot version: 0.117.0 (api) - DEBUG - GET to endpoint: direct_v2/get_presence/ returned response: <Response [200]>
2021-02-17 19:41:22,127 - instabot version: 0.117.0 (api) - DEBUG - GET to endpoint: direct_v2/inbox/?visual_message_return_type=unseen&thread_message_limit=10&persistentBadging=true&limit=20 returned response: <Response [200]>
2021-02-17 19:41:22,566 - instabot version: 0.117.0 (api) - DEBUG - GET to endpoint: direct_v2/inbox/?visual_message_return_type=unseen&persistentBadging=true&limit=0 returned response: <Response [200]>
2021-02-17 19:41:23,799 - instabot version: 0.117.0 (api) - DEBUG - GET to endpoint: discover/topical_explore/?is_prefetch=true&omit_cover_media=true&use_sectional_payload=true&timezone_offset=0&session_id=df2ca819-7a65-4ec4-9d43-70893f5af348&include_fixed_destinations=true returned response: <Response [200]>
2021-02-17 19:41:24,216 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: notifications/badge/ returned response: <Response [200]>
2021-02-17 19:41:24,701 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qp/batch_fetch/ returned response: <Response [200]>
2021-02-17 19:41:24,733 - instabot version: 0.117.0 (bot_checkpoint) - DEBUG - Loading Checkpoint file from: C:\Users\User\Desktop\projects\image editor/config/deepfriedmemes14.checkpoint
2021-02-17 19:42:05,144 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: media/configure/? returned response: <Response [200]>
2021-02-17 19:42:09,202 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/expose/ returned response: <Response [200]>
2021-02-17 19:42:09,218 - instabot version: 0.117.0 (bot_photo) - INFO - Photo 'C:/Users/User/Desktop/projects/image editor/deepfried/13.png' is uploaded.
2021-02-17 19:43:12,190 - instabot version: 0.117.0 (api) - WARNING - HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/media/configure/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001A3E4F1FFD0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2021-02-17 19:43:48,397 - instabot version: 0.117.0 (api) - WARNING - HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/media/configure/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001A3E4F2A3D0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2021-02-17 19:44:08,509 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: media/configure/? returned response: <Response [200]>
2021-02-17 19:44:29,570 - instabot version: 0.117.0 (api) - WARNING - HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/qe/expose/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001A3E4F2A730>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2021-02-17 19:44:29,655 - instabot version: 0.117.0 (bot_photo) - INFO - Photo 'C:/Users/User/Desktop/projects/image editor/deepfried/14.png' is uploaded.
2021-02-17 19:45:17,413 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: media/configure/? returned response: <Response [200]>
2021-02-17 19:45:38,461 - instabot version: 0.117.0 (api) - WARNING - HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/qe/expose/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001A3E4F2AC40>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2021-02-17 19:45:38,476 - instabot version: 0.117.0 (bot_photo) - INFO - Photo 'C:/Users/User/Desktop/projects/image editor/deepfried/15.png' is uploaded.
2021-02-17 19:46:39,657 - instabot version: 0.117.0 (api) - WARNING - HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/media/configure/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001A3E4F24640>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2021-02-17 19:46:59,591 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: media/configure/? returned response: <Response [200]>
2021-02-17 19:47:01,442 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/expose/ returned response: <Response [200]>
2021-02-17 19:47:01,442 - instabot version: 0.117.0 (bot_photo) - INFO - Photo 'C:/Users/User/Desktop/projects/image editor/deepfried/16.png' is uploaded.
2021-02-17 19:47:44,251 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: media/configure/? returned response: <Response [200]>
2021-02-17 19:47:45,871 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/expose/ returned response: <Response [200]>
2021-02-17 19:47:45,871 - instabot version: 0.117.0 (bot_photo) - INFO - Photo 'C:/Users/User/Desktop/projects/image editor/deepfried/17.png' is uploaded.
2021-02-17 19:48:47,008 - instabot version: 0.117.0 (api) - WARNING - HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/media/configure/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001A3E4F2AE20>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2021-02-17 19:49:06,496 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: media/configure/? returned response: <Response [200]>
2021-02-17 19:49:07,381 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/expose/ returned response: <Response [200]>
2021-02-17 19:49:07,381 - instabot version: 0.117.0 (bot_photo) - INFO - Photo 'C:/Users/User/Desktop/projects/image editor/deepfried/19.png' is uploaded.
2021-02-17 19:50:06,096 - instabot version: 0.117.0 (api) - WARNING - HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/media/configure/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001A3E4F1F970>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2021-02-17 19:50:24,256 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: media/configure/? returned response: <Response [200]>
2021-02-17 19:50:45,296 - instabot version: 0.117.0 (api) - WARNING - HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/qe/expose/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001A3E4F24370>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2021-02-17 19:50:45,311 - instabot version: 0.117.0 (bot_photo) - INFO - Photo 'C:/Users/User/Desktop/projects/image editor/deepfried/20.png' is uploaded.
2021-02-17 19:51:29,094 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: media/configure/? returned response: <Response [200]>
2021-02-17 19:51:30,341 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/expose/ returned response: <Response [200]>
2021-02-17 19:51:30,348 - instabot version: 0.117.0 (bot_photo) - INFO - Photo 'C:/Users/User/Desktop/projects/image editor/deepfried/21.png' is uploaded.
2021-02-17 19:52:13,810 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: media/configure/? returned response: <Response [200]>
2021-02-17 19:52:15,183 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/expose/ returned response: <Response [200]>
2021-02-17 19:52:15,183 - instabot version: 0.117.0 (bot_photo) - INFO - Photo 'C:/Users/User/Desktop/projects/image editor/deepfried/22.png' is uploaded.
2021-02-17 19:53:00,447 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: media/configure/? returned response: <Response [200]>
2021-02-17 19:53:01,863 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/expose/ returned response: <Response [200]>
2021-02-17 19:53:01,879 - instabot version: 0.117.0 (bot_photo) - INFO - Photo 'C:/Users/User/Desktop/projects/image editor/deepfried/23.png' is uploaded.
2021-02-17 19:54:03,019 - instabot version: 0.117.0 (api) - WARNING - HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/media/configure/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001A3E4F247C0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2021-02-17 19:54:39,057 - instabot version: 0.117.0 (api) - WARNING - HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/media/configure/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001A3E4F24190>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2021-02-17 19:54:58,522 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: media/configure/? returned response: <Response [200]>
2021-02-17 19:55:00,869 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/expose/ returned response: <Response [200]>
2021-02-17 19:55:00,869 - instabot version: 0.117.0 (bot_photo) - INFO - Photo 'C:/Users/User/Desktop/projects/image editor/deepfried/24.png' is uploaded.
2021-02-17 19:55:45,199 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: media/configure/? returned response: <Response [200]>
2021-02-17 19:55:46,469 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/expose/ returned response: <Response [200]>
2021-02-17 19:55:46,484 - instabot version: 0.117.0 (bot_photo) - INFO - Photo 'C:/Users/User/Desktop/projects/image editor/deepfried/25.png' is uploaded.
2021-02-17 19:56:46,284 - instabot version: 0.117.0 (api) - WARNING - HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/media/configure/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001A3E4F1FC40>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2021-02-17 19:57:05,595 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: media/configure/? returned response: <Response [200]>
2021-02-17 19:57:07,442 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/expose/ returned response: <Response [200]>
2021-02-17 19:57:07,442 - instabot version: 0.117.0 (bot_photo) - INFO - Photo 'C:/Users/User/Desktop/projects/image editor/deepfried/3.png' is uploaded.
2021-02-17 19:57:53,214 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: media/configure/? returned response: <Response [200]>
2021-02-17 19:57:54,553 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/expose/ returned response: <Response [200]>
2021-02-17 19:57:54,553 - instabot version: 0.117.0 (bot_photo) - INFO - Photo 'C:/Users/User/Desktop/projects/image editor/deepfried/6.png' is uploaded.
2021-02-17 19:58:38,978 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: media/configure/? returned response: <Response [200]>
2021-02-17 19:58:40,894 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/expose/ returned response: <Response [200]>
2021-02-17 19:58:40,910 - instabot version: 0.117.0 (bot_photo) - INFO - Photo 'C:/Users/User/Desktop/projects/image editor/deepfried/7.png' is uploaded.
2021-02-17 19:59:26,143 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: media/configure/? returned response: <Response [200]>
2021-02-17 19:59:29,359 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/expose/ returned response: <Response [200]>
2021-02-17 19:59:29,359 - instabot version: 0.117.0 (bot_photo) - INFO - Photo 'C:/Users/User/Desktop/projects/image editor/deepfried/8.png' is uploaded.
2021-02-17 20:00:12,767 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: media/configure/? returned response: <Response [200]>
2021-02-17 20:00:13,231 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/expose/ returned response: <Response [200]>
2021-02-17 20:00:13,231 - instabot version: 0.117.0 (bot_photo) - INFO - Photo 'C:/Users/User/Desktop/projects/image editor/deepfried/9.png' is uploaded.
